### ISSUE TITLE
Container status as exited

### ISSUE THREAD

**Issue by imranrazakhan** [rmohr/docker-activemq#29]
if we changed 

CMD ["/bin/sh", "-c", "/opt/apache/activemq/bin/activemq console"]
to 
CMD ["/bin/sh", "-c", "/opt/apache/activemq/bin/activemq start"]

why container status is showing as exited not running?

**Comment by rmohr** [comment]
Hi,

Because activemq tries to start as a daemon. From dockers perspective the active process disappears and it will therefore stop the container. Why can't you use `console`?
