### ISSUE TITLE
Maximum memory definition missed

### ISSUE THREAD

**Issue by demon101** [rmohr/docker-activemq#38]
As I can see, there is no possibility for memory configuration

In the disaster37/activemq it tunned by wrapper settings:

> self.replace_all(ACTIVEMQ_HOME + "/bin/linux-x86-64/wrapper.conf", "#?wrapper\.java\.initmemory=\d+", 'wrapper.java.initmemory=' + str(minMemoryInMB))
>         self.replace_all(ACTIVEMQ_HOME + "/bin/linux-x86-64/wrapper.conf", "#?wrapper\.java\.maxmemory=\d+", 'wrapper.java.maxmemory=' + str(maxMemoryInMb))

Maybe I just missed this feature?

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
