### ISSUE TITLE
set activemq.xml file path from env

### ISSUE THREAD

**Issue by herzcthu** [rmohr/docker-activemq#39]
I'm trying to set different file path for activemq.xml config file.
I've tried to set COMMANDLIND_ARGS=xbean:file:./myconfig.xml or ACTIVEMQ_OPTS=xbean:file:./myconfig.xml 
Both did not work.
How can I set different file path for config file?

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
