### ISSUE TITLE
ps: unrecognized option: p

### ISSUE THREAD

**Issue by herzcthu** [rmohr/docker-activemq#40]
I'm using activemq alpine linux image rmohr/activemq:5.15.6-alpine
I see ps: unrecognized option: p on startup
I find out that alpine ps is from busybox and it is not included -p switch for ps.
activemq startup script is using ps -p to see JAVA process
adding procps in image might solve that 
```
apk --no-cache add procps
```

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
