### ISSUE TITLE
user activemq problem AWS with efs

### ISSUE THREAD

**Issue by casper5822** [rmohr/docker-activemq#43]
Hello,
the chown activemq:activemq with user activemq have problems when deploying on a amazon efs binding volumes (they work with root user and aws changes the volume ownership so we take a permission denied on pid in data folder). 
Is there any way to set the  activemq dockerfile user with parameters?

Thank you.

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
