### ISSUE TITLE
add ssl support

### ISSUE THREAD

**Issue by cforce** [rmohr/docker-activemq#44]
ssl://localhost:7443

Using keytool, create a certificate for the broker:
* `keytool -genkey -alias broker -keyalg RSA -keystore broker.ks`
Export the broker’s certificate so it can be shared with clients:
* `keytool -export -alias broker -keystore broker.ks -file broker_cert`
Create a certificate/keystore for the client:
* `keytool -genkey -alias client -keyalg RSA -keystore client.ks`
Create a truststore for the client, and import the broker’s certificate. This establishes that the client “trusts” the broker:
* `keytool -import -alias broker -keystore client.ts -file broker_cert`

Before starting the broker’s VM set the ACTIVEMQ_SSL_OPTS environment variable so that it knows to use the broker keystore. (note that in previous versions of ActiveMQ this property was called SSL_OPTS in some scripts. As of v5.12.0 all scripts use ACTIVEMQ_SSL_OPTS)

`export ACTIVEMQ_SSL_OPTS = -Djavax.net.ssl.keyStore=/path/to/broker.ks -Djavax.net.ssl.keyStorePassword=password`

**Comment by ambs** [comment]
Is there any image configured by default for SSL support? It would be neat.

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
