### ISSUE TITLE
INFO: Starting in foreground, this is just for debugging purposes (stop process by pressing CTRL+C)

### ISSUE THREAD

**Issue by Linuxea** [rmohr/docker-activemq#45]
the ctrl + z doesn't work after server start

![image](https://user-images.githubusercontent.com/18577499/64221719-5a184380-cf00-11e9-9c8e-a0a4a55d46bb.png)

**Comment by walteruzzu** [comment]
I have the same issue. Why does it not work with CTRL+C or CTRL+Z ?
Is there a quick way to terminate the process other than killing the container?

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
