### ISSUE TITLE
override login credentials 

### ISSUE THREAD

**Issue by eccar28** [rmohr/docker-activemq#46]
I want to override the default user/password (admin/admin).
I tried with:
 docker run -p 61616:61616 -p 8161:8161   -e "activemq.username=user" -e "activemq.password=Password"    rmohr/activemq

but it won't help..

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
