### ISSUE TITLE
Plz tell me the passwd of root ?

### ISSUE THREAD

**Issue by duckducko** [rmohr/docker-activemq#49]
as the title said.

**Comment by ctonsing** [comment]
I would also like to know this... Or some other way of installing vi or some text editor so that I can edit the /opt/apache-activemq-5.15.6/conf/jetty-realm.properties file so that the admin password can be changed?

**Comment by ctonsing** [comment]
> I would also like to know this... Or some other way of installing vi or some text editor so that I can edit the /opt/apache-activemq-5.15.6/conf/jetty-realm.properties file so that the admin password can be changed?

Oops, I guess one can just do
`docker exec -u root -it active_mq_image_name /bin/bash`

Then one is logged in as root...

**Comment by duckducko** [comment]
> > I would also like to know this... Or some other way of installing vi or some text editor so that I can edit the /opt/apache-activemq-5.15.6/conf/jetty-realm.properties file so that the admin password can be changed?
> 
> Oops, I guess one can just do
> `docker exec -u root -it active_mq_image_name /bin/bash`
> 
> Then one is logged in as root...

THX..... XD
