### ISSUE TITLE
For persistence you need to own the folders

### ISSUE THREAD

**Issue by gorgia** [rmohr/docker-activemq#50]
After exiting the intermediate alpine image you have to chmod the persistence folders in order to use them in another container (the one with activemq running).
I know that it may sound obvious, but still I have lost some time for this reason. Maybe you could add it as a remainder in the readme.
Thanks.

**Comment by sibtainabbas10** [comment]
Hi gorgia,

I ran the following commands as suggested in the README

```
docker run --user root --rm -ti \
  -v /home/t919484/activemq/conf:/mnt/conf \
  -v /home/t919484/activemq/data:/mnt/data \
  rmohr/activemq:5.15.4-alpine /bin/sh

chown activemq:activemq /mnt/conf
chown activemq:activemq /opt/activemq/data
chown activemq:activemq /mnt/data
cp -a /opt/activemq/conf/* /mnt/conf/
cp -a /opt/activemq/data/* /mnt/data/
exit

docker run -p 61616:61616 -p 8161:8161 --name activemq-vol -d \
           -v /home/t919484/activemq/conf:/opt/activemq/conf \
           -v /home/t919484/activemq/data:/opt/activemq/data \
           rmohr/activemq
```

But I always get the following error:

> log4j:ERROR setFile(null,true) call failed.
> java.io.FileNotFoundException: /opt/activemq/data/audit.log (Permission denied)

Can you please tell me how you managed to solve this?

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
