### ISSUE TITLE
Move to maintained base Java docker image

### ISSUE THREAD

**Issue by skjolber** [rmohr/docker-activemq#51]
Change from Openjdk (by Oracle) to AdoptOpenJDK base images. The latest docker images do have a few security issues to them already.

**Comment by skjolber** [comment]
@rmohr any hope for this issue?

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
