### ISSUE TITLE
cli utilities not working

### ISSUE THREAD

**Issue by wolftobias** [rmohr/docker-activemq#55]
After connecting into the docker container, no cli utiliy is working except create.
This error message comes up, even after setting jmx=true in activemq.xml.

``
Broker not available at: service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi
``

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
