### ISSUE TITLE
How i can add -XX:+PrintGCDetails to get GC details

### ISSUE THREAD

**Issue by imranrazakhan** [rmohr/docker-activemq#58]
I am facing some performance issues so i want to enable -XX:+PrintGCDetails, is there any option to do this?

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
