### ISSUE TITLE
Support for 5.15.0

### ISSUE THREAD

**Issue by zeeveener** [rmohr/docker-activemq#59]
As per [AmazonMQ Documentation](https://aws.amazon.com/amazon-mq/faqs/)

> Q: Which versions of ActiveMQ does Amazon MQ support?
> 
> Amazon MQ provides support for ActiveMQ versions 5.15.0, 5.15.6, 5.15.8, 5.15.9, and 5.15.10.

It appears that there is no support in this repository for version **5.15.0**.

Unfortunately, this means that anyone who is currently stuck using the AmazonMQ equivalent of ActiveMQ 5.15.0 and wants to start the transition to using Docker for their application development and deployment must manually generate Dockerfiles for that version of ActiveMQ.

I am creating this issue to capture this reality and hope either to see the change realized by someone else or to make the change myself depending on my personal schedule.

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
