### ISSUE TITLE
Support for ActiveMQ 5.16.0 (Jul 1, 2020)

### ISSUE THREAD

**Issue by carantunes** [rmohr/docker-activemq#60]
Hi, great work!
Please consider releasing the latest activemq.

Latest release is ActiveMQ 5.16.0 (Jul 1, 2020)

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
