### ISSUE TITLE
Question - Can I query the queues using REST?

### ISSUE THREAD

**Issue by guilhermecgs** [rmohr/docker-activemq#62]
Hi folks,

I need a rest api to query/search messages in the queue. Can I use this image?
Can someone recommend one if not?

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
