### ISSUE TITLE
What is the user and password?

### ISSUE THREAD

**Issue by mikeSxz** [rmohr/docker-activemq#64]
I want to get access to console, but it ask for a user and password, could you share that info please?

**Comment by notarun** [comment]
@mikeSxz 
user: `admin`
pass: `admin`

**Comment by HWiese1980** [comment]
This information should be in the README if you ask me

**Comment by timb33** [comment]
can someone update the readme with how to change the default password please?

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
