### ISSUE TITLE
Support for ActiveMQ 15.17.0

### ISSUE THREAD

**Issue by petr-ujezdsky** [rmohr/docker-activemq#71]
Here is `Dockerfile` for version 5.17.0. The new version does not work inside symlink so it has to be directly in directory.

```
FROM openjdk:11-jre

ENV ACTIVEMQ_VERSION 5.17.0
ENV ACTIVEMQ apache-activemq-$ACTIVEMQ_VERSION
ENV ACTIVEMQ_TCP=61616 ACTIVEMQ_AMQP=5672 ACTIVEMQ_STOMP=61613 ACTIVEMQ_MQTT=1883 ACTIVEMQ_WS=61614 ACTIVEMQ_UI=8161
ENV SHA512_VAL=d3252df7528b7000fceaf0a8b45c65216010467fea775bb3219ef04aaa659156f4c87982eb11a6982204d2737b9cc2b93efac88b651f1447270528bf62b1e238

ENV ACTIVEMQ_HOME /opt/activemq


RUN curl "https://archive.apache.org/dist/activemq/$ACTIVEMQ_VERSION/$ACTIVEMQ-bin.tar.gz" -o $ACTIVEMQ-bin.tar.gz

# Validate checksum
RUN if [ "$SHA512_VAL" != "$(sha512sum $ACTIVEMQ-bin.tar.gz | awk '{print($1)}')" ];\
    then \
        echo "sha512 values doesn't match! exiting."  && \
        exit 1; \
    fi;

RUN tar xzf $ACTIVEMQ-bin.tar.gz -C  /opt && \
    mv /opt/$ACTIVEMQ $ACTIVEMQ_HOME && \
    useradd -r -M -d $ACTIVEMQ_HOME activemq && \
    chown -h activemq:activemq $ACTIVEMQ_HOME 

USER activemq

WORKDIR $ACTIVEMQ_HOME
EXPOSE $ACTIVEMQ_TCP $ACTIVEMQ_AMQP $ACTIVEMQ_STOMP $ACTIVEMQ_MQTT $ACTIVEMQ_WS $ACTIVEMQ_UI

CMD ["/bin/sh", "-c", "bin/activemq console"]
```

I would create a PR but the repository can not be forked anymore and it also seems to be not maintained anymore.
But I see @rmohr active in other areas, so maybe he could explain or make some statement on future of this repo? (please :) )

I have also reported the symlink issue in upstream https://issues.apache.org/jira/browse/AMQ-8591.

**Comment by rmohr** [comment]
Hi, sadly I don't have the time to follow up on this repo. I am not using this repo anymore for a very long time and maintained it much longer than I needed it. I also tried to hand it over to the activemq maintainers, but they had different container-publish plans (not sure if there is an officially maintained way now).

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
