### ISSUE TITLE
Change docker scripts to the Apache license (like ActiveMQ)

### ISSUE THREAD

**Issue by iemejia** [rmohr/docker-activemq#8]
Would it be possible to switch the license from MIT to Apache.
I consider that given that this is for an Apache project it should share the similar type of license.
And this way we can eventually contribute these changes upstream.

**Comment by rmohr** [comment]
> Would it be possible to switch the license from MIT to Apache.
> I consider that given that this is for an Apache project it should share the similar type of license.
> And this way we can eventually contribute these changes upstream.

I do not really have a problem with a license change. I can't even remember why I chose MIT over Apache here. Would you try to contribute these Dockerfiles as official activemq docker images?

**Comment by iemejia** [comment]
Yes, this is my ultimate goal. Because right now your images are the simplest ones out there (not the most used, but the ones most up to date, easiest to integrate, and slim too, via my latest PR ;)).

**Comment by iemejia** [comment]
Fixed by PR #13
