### ISSUE TITLE
Make this project an official docker image

### ISSUE THREAD

**Issue by iemejia** [rmohr/docker-activemq#9]
I want to help with this process, are you interested in helping with maintenance if we achieve it ?

**Comment by rmohr** [comment]
Sure, happy to do so. We can ask the activemq people on their mailing list/forum when we have sorted out #7

**Comment by iemejia** [comment]
Cool, my current boss is an ActiveMQ committer so I can ping him for some extra support. I don't know if they have some sort of contrib in their repo, if it is the case would you agree to move the code there ? (this will give the code more visibility (and some possible extra maintainers).

**Comment by iemejia** [comment]
For reference I contacted upstream to see if they are interested. I didn't copy you in the email because I was afraid you could be spammed afterwards.

https://lists.apache.org/thread.html/d03fff2a58a00e7ff2ceb6e84e0b19bdf1559026142a18b7a881b430@%3Cdev.activemq.apache.org%3E

**Comment by rmohr** [comment]
Too bad that this did not work out.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.
